spring.application.name=AuthenticationService

#spring.datasource.url=jdbc:mysql://localhost:3306/userDetails_db
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# JWT secret (change in production)
jwt.secret=kyjNm25NVKORbEbOwpniPJplL9savyuq4CujdCBX+fR6mSvkj3m+UwLqlpT0oWXVEb8r7HuFQtZuU3PSTjTEzA==
jwt.expirationMs=3600000

# Swagger UI path (springdoc)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

server.port=8089

